### ISSUE TITLE
Delete this please

### ISSUE THREAD

**Issue by Pixelry0** [MediumDifficulty/mcvideo-3#1]

**Comment by Linter2** [comment]
I'm not quite sure what this error could be. It might be that it needs access to all files in the "bin" folder in the ffmpeg installation.

Sorry if this is the case, I should have added it to the readme

**Comment by Pixelry0** [comment]
![image](https://github.com/MediumDifficulty/mcvideo-3/assets/53848296/27f344ee-adae-43c9-9a13-65bb8a690ab1)
After adding the files I am still getting driver errors.

**Comment by Pixelry0** [comment]
> I'm not quite sure what this error could be. It might be that it needs access to all files in the "bin" folder in the ffmpeg installation.
> 
> Sorry if this is the case, I should have added it to the readme

Is their a specific bin folder I have to download?

**Comment by Linter2** [comment]
It's one of directories in the archives when you download ffmpeg (I used 
ffmpeg-release-full-shared.7z from [here](https://www.gyan.dev/ffmpeg/builds/))

**Comment by Pixelry0** [comment]
Thank you I got it working.

**Comment by Pixelry0** [comment]
I have a new problem now after opening the program and running it with a 23 second test video after 1 hour it has made no progress and does not seem to be doing anything here is the command I used
mcvideo-3-0.2.0.exe --input test.mp4 --width 320 --height 240 --clip-length 23

**Comment by Linter2** [comment]
Has it worked before this? Also, when does it stop making progress? (Can you join the server?)

Sorry for the late reply!

**Comment by Pixelry0** [comment]
> Has it worked before this? Also, when does it stop making progress? (Can you join the server?)
> 
> Sorry for the late reply!

No it did not even create the server it did nothing after I ran the command it does not show any progress being made

**Comment by Pixelry0** [comment]
Update: It works!
